### ISSUE TITLE
Failed to load on server

### ISSUE THREAD

**Issue by Tempest-5ky** [jenchanws/discraft#1]
Hello hello! Just here to report an issue where the mod fails to load on a Fabric 1.19.2 server!

The error is as follows:
`[00:20:04] [main/ERROR]: DisCraft failed to load`

`[00:20:04] [main/INFO]: [STDERR]: java.lang.NullPointerException`

`[00:20:04] [main/INFO]: [STDERR]: 	at littlechasiu.discraft.DisCraft.initDiscord(DisCraft.kt:105)`

`[00:20:04] [main/INFO]: [STDERR]: 	at littlechasiu.discraft.DisCraftModKt.init(DisCraftMod.kt:13)`

`[00:20:04] [main/INFO]: [STDERR]: 	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)`

`[00:20:04] [main/INFO]: [STDERR]: 	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy37.onInitialize(Unknown Source)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:101)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)`

`[00:20:04] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)`

Let me know if any additional info is needed, I will happily provide it!

**Comment by Tempest-5ky** [comment]
Something that may be significant: This server is also using https://modrinth.com/mod/autowhitelist-lite
